port: 80 # do NOT use HTTP on port 443, and HTTPS on port 80.

listen: "all" 
# options: all, local
# local: no clue why would you need local.
# all: is if you want every device to be able to access this

alerts: true # better console.logs

ratelimit: 12 # how many times message can be sent a minute
# below is https setup

https: false # false uses http. true uses https.
crtlocation: "ssl-certs/server.key" # put your crt location
keylocation: "ssl-certs/server.crt" # put your key location